### ISSUE TITLE
Browser's features

### ISSUE THREAD

**Issue by dimqua** [proninyaroslav/abrowser-android#1]
В чем отличия этого браузера от GNU IceCat, например? 
Возможно, стоит написать немного больше о том, что это браузер такой и добавить его в F-Droid? Предполагаю, они не будут против и сами с этим помочь.

**Comment by proninyaroslav** [comment]
Здравствуйте. GNU IceCat использует Firefox ESR версии, в данном случае используются последние свежие версии Firefox. Не удалены некоторые возможности, например, синхронизация. LibreJS не используется по умолчанию. То есть в целом Abrowser более "нейтральный" и идёт на некоторые компромиссы между приватностью и юзабилити.

Инфо об этом браузере есть на официальной странице https://trisquel.info/en/wiki/abrowser-help, ссылка в README есть (также тред в Reddit https://www.reddit.com/r/trisquel/comments/2jxaxs/what_is_the_difference_between_abrowser_and_icecat/)

На счёт F-Droid: для сборки IceCat используется специально настроенное окружение, которое было сделано исключительно для IceCat. В целом сборка Firefox нетривиальна, сопряжена со многими особенностями которые я стараюсь учесть в данном скрипте. Тем более что это не стабильный ESR. Как вариант я бы рассматривал собственный сервер для сборки, не используя серверы F-Droid, чтобы иметь полный дсотуп к процессу сборки для отладки. Возможно такой сервер появится у меня в скором времени, поскольку есть нужда собирать ещё одно Android-приложение

**Comment by dimqua** [comment]
Тогда, выходит, что мобильная версия ближе к Fennec F-Droid?
>Как вариант я бы рассматривал собственный сервер для сборки, не используя серверы F-Droid

Но ведь F-Droid обеспечивает не только сборку, но и доставку обновлений, что в случае с браузером очень важно. Хотя, в принципе, и необязательно добавлять в основной репозиторий, я бы предложил добавить в [IzzyOnDroid](https://apt.izzysoft.de/fdroid/), это неофицальный. Для этого, по сути, ничего и не нужно, кроме публикации сборок на странице github.com/proninyaroslav/abrowser-android/releases, а они там уже есть. :-)

**Comment by proninyaroslav** [comment]
>Тогда, выходит, что мобильная версия ближе к Fennec F-Droid?

Да, но не знаю насколько он очищен по сравнению с Abrowser.

>Но ведь F-Droid обеспечивает не только сборку, но и доставку обновлений

С доставкой никаких проблем не будет.

>я бы предложил добавить в IzzyOnDroid, это неофицальный

Интересно, не слышал.

**Comment by dimqua** [comment]
Под доставкой я имел ввиду не на гитхаб, само собой, а на устройства пользователей. В Firefox ведь нет никаких встроенных средств проверки и загрузки обновлений на Android.

Еще замечу, что наличие приложения в F-Droid не означает, разумеется, что разработчику нельзя самому публиковать (отлаживать и т.п.) свои сборки где-либо еще. Многие так и делают, а не полагаются только на F-Droid. Другое дело, что если дело дойдет до официального репозитория, то приложение из IzzyOnDroid удалят, скорее всего.

Оставил запрос: https://gitlab.com/IzzyOnDroid/repo/issues/49

**Comment by proninyaroslav** [comment]
> Под доставкой я имел ввиду не на гитхаб, само собой, а на устройства пользователей.

Я имел ввиду что если использовать fdroidserver то можно собирать и подписывать приложение на собственном сервере (и не ждать нескольких суток) и при этом сервер будет частью инфраструктуры F-Droid.
