### ISSUE TITLE
No ARM/AArch64 APKs appear in Repo List

### ISSUE THREAD

**Issue by kowith337** [proninyaroslav/abrowser-android#2]
This must be an external issue but I cannot open ticket there, so I just report here.

The unofficial Firefox Repo list for F-Droid doesn't provide ARM/AARch64 APKs, current solution is directly download from your releases page.

![noarm](https://i.imgur.com/rsAahFK.jpeg)

**Comment by proninyaroslav** [comment]
It must provide versions for all architectures. Perhaps you should somehow get in touch with the maintainer of this repository.

**Comment by esmoak** [comment]
I left a message for him (rfc2882) on the Fdroid forum about this. I don’t know another way to contact him. 

He had a support thread there that got closed since the last reply was outdated.

**Comment by kowith337** [comment]
Sorry for late report, but it seems like I can see ARM built now, both in Aurora Droid and F-Droid.

Thanks again.
